<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="LocalDb" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="Argon" />
    <PackageReference Include="DiffEngine" />
    <PackageReference Include="EmptyFiles" />
    <PackageReference Include="SimpleInfoName" />
    <PackageReference Include="Verify" />
    <PackageReference Include="Verify.SqlServer" />
    <PackageReference Include="Verify.MicrosoftLogging" />
    <PackageReference Include="Verify.AspNetCore" />
    <PackageReference Include="coverlet.collector" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
    <PackageReference Include="MarkdownSnippets.MsBuild" PrivateAssets="all" />
    <ProjectReference Include="..\Delta.SqlServer\Delta.SqlServer.csproj" />
    <ProjectReference Include="..\Delta\Delta.csproj" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
    <ProjectReference Include="..\WebApplicationPostgres\WebApplicationPostgres.csproj" />
    <ProjectReference Include="..\WebApplicationSqlServer\WebApplicationSqlServer.csproj" />
  </ItemGroup>
</Project>
